server:
  port: 8888

spring:
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: http://hoangdh.gitlab.com/root/server.git
          default-label: main
          username: root
          password: glpat-tLOLYU7WejzNJrEviu4c7W86MQp1OjEH.01.0w06m930m
          search-paths:
            - common
            - '{application}'
          clone-on-start: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always