server:
  port: 8888

management:
                                       endpoints:
    web:
      exposure:
        include: health,info,env

        include=health,info,prometheus:endpoint:
    health:
      show-details: when_authorized
      probes:
        enabled: true

spring:
  application:
    name: cloud-config-server
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://git.viettelpost.vn/f2c/backend/f2c-config.git
          default-label: main
          search-paths:
            - common
            - '{application}'
          clone-on-start: true

  management.endpoints.web.exposure.include=health,info,prometheus