name: OWASP ZAP Security Scan

on:
  push:
  workflow_dispatch: 

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Quét lỗ hổng bảo mật
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # BƯỚC MỚI: Mở khóa quyền ghi cho Docker Container
      - name: Cấp quyền ghi thư mục cho ZAP
        run: chmod -R 777 $GITHUB_WORKSPACE

      - name: Chạy OWASP ZAP Baseline Scan
        # Đã cập nhật lên phiên bản v0.12.0 để sửa lỗi Artifact
        uses: zaproxy/action-baseline@v0.12.0
        with:
          # Đừng quên thay dòng này bằng IP/Domain thực tế của bạn nhé
          target: 'http://ip-cua-staging-server' 
          fail_action: false
