name: Kịch bản CI/CD và Quét Bảo mật (GitHub Actions)

# 1. Kích hoạt khi có người push code lên nhánh stag
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest # GitHub cấp sẵn cho bạn một máy ảo Ubuntu miễn phí

    steps:
      # Bước 1: Tải code về
      - name: Checkout code
        uses: actions/checkout@v3

      # Bước 2: Bắn tín hiệu sang Jenkins của bạn
      - name: Gọi Jenkins chạy Test
        run: |
          echo "Đang gọi Jenkins tại hoangdang.jenkins.com..."
          curl -X POST "http://hoangdang.jenkins.com/job/Run-Test-Stag/build?token=YOUR_JENKINS_TOKEN"

      # Bước 3: Chạy ZAP Scan (Action chính chủ)
      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'http://ip-cua-staging-server' # Thay IP thật vào đây
